deepgenomics/GenomeKit

tests/test_gk_data.py

chore: avoid CI failure on conda-forge

---

tests/test_twobitutils.py

chore: skip windows tests correctly

---

tests/test_twobitutils.py

to see if it affected the linux build
Release-As: 4.1.5

chore: revert the windows test change

---

tests/test_twobitutils.py

chore: avoid import on Windows

---

CMakeLists.txt
docs/develop.rst
tests/test_twobitutils.py
tests/test_variant_table.py

chore: skip bioconda-dependant tests on conda-forge

---

genomekit_dev.yml

see https://github.com/googleapis/python-storage/commit/d02098e6d5f656f9802cf0a494b507d77b065be7

chore: match_glob minver

---

.github/actions/configure-conda/action.yaml
.github/actions/create-conda-env/action.yaml
.github/actions/install-mamba/action.yaml
.github/workflows/run-tests.yaml
README.md
conda-recipe/conda_build_config.yaml

just linux and osx on amd64 for now
tests are parallelized per os and python version

chore: run unit tests on push

---

docs/quickstart.rst
genome_kit/data_manager.py

feat: use new dedicated requester-pays public bucket

---

setup/c_ext.py

remove arch tuning and allow conda-forge to decide instruction set

chore: allow arm64

---

genome_kit/data_manager.py

fix: allow local-only files to be loaded

---

README.md
setup.py

docs: restore and document link to versionized docs

---

starter/build.sh

chore: avoid wget ftp compat issues

---

docs-src/quickstart.rst
genome_kit/gk_data.py
src/py_genome.cpp
src/refg.cpp
src/refg.h
starter/build.sh

feat: read/write files for refg name hash lookups

---

src/refg.cpp
src/refg.h

fix: avoid accessing released memory

---

src/py_genome_dna.cpp
tests/test_genome_dna.py

fix: check genome.dna(Interval) arg type

---

genome_kit/genome_track.py
src/genome_track.cpp
src/genome_track.h
src/py_genome_track.cpp
tests/test_genome_track.py

this allows for utilities to dump out/merge gtracks
as @ovesh is out on vacation, feel free to review at least the usage

feat(gtrack): interval iteration

---

genome_kit/genome_track.py
src/py_genome_track.cpp
tests/test_genome_track.py

useful for reducing copying overhead when merging tracks

feat(gtrack): inplace output

---

src/genome_track.h

modern compilers (gcc 12) already unroll and produce identical assembly
note: constant progagation of dim however still has a large benefit (170ms vs 98ms when querying all of chr1 with dim=1).

refactor(track): remove manual unrolling

---

.github/workflows/publish-docs.yaml

sphinx>=8 causes error "sphinx 'style' is undefined"
e.g https://github.com/deepgenomics/GenomeKit/actions/runs/10359784764

chore: fix publish-docs failure

---

genome_kit/data_manager.py

fix(data): don't swallow exception depending on log level

---

.github/workflows/run-tests.yaml
conda-recipe/conda_build_config.yaml
genomekit_dev.yml
setup.py

no longer supported by conda-forge

chore: deprecate py38

---

genome_kit/genome.py
genome_kit/variant_genome.py
src/genome_dna.h
src/py_genome_dna.cpp
tests/test_genome.py
tests/test_genome_dna.py
tests/test_variant_genome.py

fix(dna): consistent allow_outside_chromosome defaults

---

setup/c_ext.py

Allow working on GK outside of a conda env

chore: specify SDK for linker as well

---

docs-src/data_org.rst
docs-src/index.rst

see https://assets.opendata.aws/aws-onboarding-handbook-for-data-providers-en-US.pdf

docs: prepare required documentation for AWS Open Data

---

docs-src/api.rst
docs-src/quickstart.rst
genome_kit/__init__.py
genome_kit/data_manager.py
genomekit_dev.yml
tests/test_data_manager.py
tests/test_gk_data.py

in preparation for using AWS Open Data S3 bucket
thus not requiring a Google Cloud account for getting the files.
depends on https://github.com/conda-forge/genomekit-feedstock/pull/59

feat: S3 data manager

---

.github/actions/curl-meta-yaml/action.yaml
.github/workflows/dockerize.yaml

also: docker image contains wrong version of python

chore: docker images published with wrong version

---

data-src/hg38.p14/NCBI/hg38.p14_RS_2024_08/fetch.sh

feat: support refseq anno GCF_000001405.40-RS_2024_08

---

conda-recipe/conda_build_config.yaml
genome_kit/_build_appris.py
genome_kit/_gk_data_config.py

feat: add appris data

---

data-src/mm39/GENCODE/vM36.basic/fetch.sh
data-src/mm39/GENCODE/vM36/fetch.sh
data-src/mm39/NCBI/mm39.RS_2024_02/fetch.sh
genome_kit/_build_appris.py
genome_kit/_gk_data_config.py
requirements.txt

feat: add mouse annos and appris

---

genome_kit/_apply_variants.py
tests/test_apply_variants.py

if the left shifted left, we need to offset the right
see https://github.com/deepgenomics/GenomeKit/pull/138/files#r1982249122

fix: handle anchor within deletions

---

data-src/hg19/GENCODE/v47lift37.basic/fetch.sh
data-src/hg19/GENCODE/v47lift37/fetch.sh
data-src/hg38.p14/GENCODE/v47.basic/fetch.sh
genome_kit/_build_appris.py

feat: add gencode.v47 adjacent annos + appris

---

.github/workflows/run-tests.yaml

avoid concurrent cache write attempts on github actions

chore: ensure build step only runs once per configuration

---

genome_kit/variant_genome.py
tests/test_serialize.py

fixes #160
VariantGenome.__getattr__ causes infinite recursion on unpickling

fix: allow VariantGenome to be serialized

---

data-src/hg19/GENCODE/v46lift37.basic/fetch.sh
data-src/hg19/GENCODE/v46lift37/fetch.sh
data-src/hg38.p14/GENCODE/v46.basic/fetch.sh
data-src/hg38.p14/GENCODE/v46/fetch.sh
docs-src/develop.rst
docs-src/genomes.rst
genome_kit/_build_appris.py
genome_kit/_build_mane.py
genome_kit/genome.py

also:
- docs: update appris/mane build instructions
- fix sphinx warnings

feat: add gencode.v46
