deepgenomics/GenomeKit

setup/c_ext.py

see https://conda-forge.org/docs/maintainer/knowledge_base/#newer-c-features-with-old-sdk
Release-As: 4.1.2

chore: avoid compile error on mac

---

tests/test_twobitutils.py

twobitreader not available on Windows
Release-As: 4.1.3

chore: avoid some tests on windows

---

tests/test_twobitutils.py
tests/test_variant_table.py

chore: avoid osx test failure

---

tests/test_gk_data.py

chore: skip gcs-dependent tests on conda-forge

---

src/variant_table.cpp

fyi there's also some warnings around the signed/unsigned wrapping in dna now

chore: unqualified style warning on newest clang

---

docs/quickstart.rst
genome_kit/data_manager.py

refg.cpp masks any exception raised in python, and the message can be misleading:
> Assembly is missing its chrom.sizes or annotation is missing its cfg file: {}

fix: provide a better hint in case of permissions error

---

docs-src/develop.rst
docs-src/quickstart.rst
genome_kit/data_manager.py
genome_kit/genome.py

Users need to set env var GK_TRACE in order to troubleshoot bucket access issues.
Otherwise users may see a confusing message like this every time: File 'ncbi_refseq.v109.chrom.sizes' not found in the GCS bucket

fix: avoid user confusion when loading annotation

---

genomekit_dev.yml

crc32c isn't available for arm64 but isn't used

fix: broken installation on osx-arm64

---

src/genome_track.cpp
src/genome_track.h
src/genome_track_io.cpp
src/py_genome_track.cpp
tests/test_genome_track.py

https://github.com/deepgenomics/GenomeKit/pull/73 was only able to output to contiguous blocks, but that's not very useful when you need to merge tracks.
eg.
```python
tracks = [gk.GenomeTrack(x) for x in filenames]
total_dim = sum(x.dim for x in tracks)
out = np.empty((len(itv), total_dim), dtype=tracks[0].dtype)
i_dim = 0
for x in tracks:
x(intv, out=[:, i_dim:i_dim+x.dim])
i_dim += x.dim
```
To keep things simple (and smaller for the binary), only positive stride steps are supported and only dim=stride is constant propagated.

fix(track): strided decoding

---

src/genome_track.cpp
src/py_genome_track.cpp
tests/test_genome_track.py

#71 added GenomeTrack.intervals. It incorrectly handles tracks where resolution>1. For resolution n, it only returns intervals corresponding to the first 1/n  of each chromosome.
see https://github.com/deepgenomics/GenomeKit/blob/e2c8dd1e5a6f7482062892b043cb613450b4cd4b/src/genome_track_io.cpp#L576-L582
for how resolutions are encoded.

fix(track): handle res>1 for track interval interrogation

---

src/genome_track.cpp
src/genome_track.h
src/genome_track_io.cpp
src/main.cpp
src/py_genome_track.cpp

the dtype enum is not strongly typed vs an int, so it can get confused with the stride argument:
```
/Users/steve/work/gk-clean/src/genome_track.h:148:7: note: candidate function
void operator()(const interval_t& c, half_t*  dst, int stride=0) const;
^
/Users/steve/work/gk-clean/src/genome_track.h:150:7: note: candidate function
void operator()(const interval_t& c, void*    dst, dtype_t dtype, int stride=0) const;
```

chore: fix ambiguous C decode fn

---

src/genome_track_io.cpp
tests/test_genome_track.py

the stride parameter
(introduced in
https://github.com/deepgenomics/GenomeKit/pull/84) was not passed correctly for the decode function to test value runs.

fix(track): sparse encoding broken

---

.github/workflows/publish-docs.yaml

introduced in #87 when previously trying to fix the docs build.

chore: bash syntax error in docs build

---

src/genome_track.h

dst modifications always need to be relative to stride, but in this case dim needs to be forward, then stride can be applied backwards

fix(track): OOB issue with negative strands on u1 tracks

---

setup/c_ext.py

setuptools broken compat, see https://github.com/pypa/setuptools/pull/4600
Error on latest release attempt: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1071695&view=logs&j=535b614b-9e28-51ef-eb67-d0aa83d01d61&t=c0e5205c-8699-555e-ce93-e93093f402f2&l=29576
setuptools not pinned, changed from 73.0.1 to 75.3.0. Hopefully should work, found similar code in other repos.

chore: fix windows build

---

docs-src/quickstart.rst

Windows users at the hackathon had issues with the script since they didn't have `grep` or `wget` from the windows command line, also saw some confusion between windows cmd and powershell users. Don't think it's a huge issue but maybe something to keep in mind since the package can be easily installed on windows but harder to use.

docs: starter_build script download

---

conda-recipe/conda_build_config.yaml
genomekit_dev.yml
setup/c_ext.py

see https://github.com/conda-forge/genomekit-feedstock/pull/52#issuecomment-2466914597
Release-As: 6.1.1
also:
- clarify purpose of conda_build_config.yaml
- remove unused private channel from env file

chore: avoid compilation errors on fmt11

---

.github/workflows/run-tests.yaml

branches-ignore references the target branch, not the source branch

chore: don't run unit tests on release-please PRs

---

.github/actions/build-gk/action.yaml
.github/workflows/dockerize.yaml
.github/workflows/publish-docs.yaml
.github/workflows/run-tests.yaml
conda-recipe/conda_build_config.yaml
genome_kit/data_manager.py
genomekit_dev.yml

Also:
- bust gk package tarballs cache on conda_build_config.yaml changes (build failure missed in #148)
- temporarily downgrade `c_stdlib_version` on osx for Github Actions to avoid build failure

chore: unpin gcs client to avoid conda conflicts

---

.github/actions/curl-meta-yaml/action.yaml

Normally meta.yaml is downloaded from the feedstock repo.
Allow quick iteration on meta.yaml in feature branches, while still failing the build if meta.yaml is accidentally committed to main.

build: allow quick iteration on meta.yaml
